version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: recipe_user_test
      POSTGRES_PASSWORD: recipe_password_test
      POSTGRES_DB: recipe_db_test
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U recipe_user_test"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:7
    environment:
      MONGO_INITDB_DATABASE: recipe_db_test
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_test:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_test:
  mongodb_data_test:
